-- ../csv/move_agg.csv

SELECT OrderNumber
, OrderTotal
, SUM(OrderTotal) OVER(ORDER BY OrderNumber
-- 最初の行から現在行まで 
RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS FISRT_TO_CURRENT
, SUM(OrderTotal) OVER(ORDER BY OrderNumber
-- 現在行から最終行まで 
RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS CURRENT_TO_LAST
, SUM(OrderTotal) OVER(ORDER BY OrderNumber
-- 最初の行から最終行まで 
RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS FIRST_TO_LAST
, SUM(OrderTotal) OVER(ORDER BY OrderNumber
-- ２行前から現在行まで 
ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS BEFORE2_TO_CURRENT
, SUM(OrderTotal) OVER(ORDER BY OrderNumber
-- ２行前から２行後まで 
ROWS BETWEEN 2 PRECEDING AND 2 FOLLOWING) AS BEFORE2_TO_CURRENT
  FROM [Item36Example].[dbo].[OrdersTable]
  ORDER BY OrderNumber
